# Generated by Django 3.0.3 on 2020-04-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200406_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
