# Generated by Django 3.0.3 on 2020-04-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200406_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
